### ISSUE TITLE
ESP8266 compilation error

### ISSUE THREAD

**Issue by Adam9850** [MartinL1/BMP388_DEV#8]
I downloaded library (v1.0.3) and tried compile a example for ESP8266 and i got this error

![image](https://user-images.githubusercontent.com/15947250/103300433-24ee0980-49ff-11eb-9ce5-67f6eb345b30.png)

I opened [SPI.h](https://github.com/esp8266/Arduino/blob/master/libraries/SPI/SPI.h) in esp8266/Arduino and found out usingInterrupt and notUsingInterrupt are not defined for ESP8266.

**Comment by MartinL1** [comment]
@Adam9850 Your pull request has now been merged, many thanks.
